server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: xpertnauman
    password: xpertnauman
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
      show_sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: amqp://localhost:5672

logging:
  level:
    org.hibernate.SQL: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  topic-exchanges:
    name: internal.exchange
  routing-keys:
    name:
      notification: notification.routing.key

