version: '3'  # Adjust the version as needed

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: xpertnauman
      POSTGRES_PASSWORD: xpertnauman
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-xpert.nauman@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-xpertnauman}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres  # Use the same network for pgadmin
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  eureka-server:
    image: hmnauman91/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

  api-gateway:
    image: hmnauman91/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - eureka-server
      - zipkin

  customer:
    image: hmnauman91/customer:1.0.1-SNAPSHOT
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=aws
      - EUREKA_SERVER_IP=13.126.112.247
      - FRAUD_SERVICE_URL=http://13.233.103.24:8081
      - NOTIFICATION_SERVICE_URL=http://52.66.234.110:8086
      - PG_PASSWORD=xpertnauman
      - PG_USER_NAME=postgres
      - POSTGRES_HOST_NAME=xpertmicroservices-dbinstance.c669qmefbqgk.ap-south-1.rds.amazonaws.com
      - RABBITMQ_IP=3.111.46.162
      - ZIPKIN_IP=3.111.46.162
    networks:
      - postgres
      - spring
    depends_on:
      - eureka-server
      - zipkin
      - rabbitmq

  fraud:
    image: hmnauman91/fraud:1.0.0-SNAPSHOT
    container_name: fraud
    ports:
      - "8081:8081"
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=aws
      - EUREKA_SERVER_IP=13.126.112.247
      - NOTIFICATION_SERVICE_URL=http://52.66.234.110:8086
      - PG_PASSWORD=xpertnauman
      - PG_USER_NAME=postgres
      - POSTGRES_HOST_NAME=xpertmicroservices-dbinstance.c669qmefbqgk.ap-south-1.rds.amazonaws.com
      - RABBITMQ_IP=3.111.46.162
      - ZIPKIN_IP=3.111.46.162
    depends_on:
      - zipkin

  notification:
    image: hmnauman91/notification:1.0.0-SNAPSHOT
    container_name: notification
    ports:
      - "8086:8086"
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=aws
      - EUREKA_SERVER_IP=13.126.112.247
      - PG_PASSWORD=xpertnauman
      - PG_USER_NAME=postgres
      - POSTGRES_HOST_NAME=xpertmicroservices-dbinstance.c669qmefbqgk.ap-south-1.rds.amazonaws.com
      - RABBITMQ_IP=3.111.46.162
      - ZIPKIN_IP=3.111.46.162
    depends_on:
      - eureka-server
      - zipkin
      - rabbitmq

networks:
  postgres:  # Define the network here
    driver: bridge
  spring:
    driver: bridge
volumes:
  postgres:
  pgadmin:
