spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST_NAME:postgres}:5432/notification
    username: ${PG_USER_NAME:xpertnauman}
    password: ${PG_PASSWORD:xpertnauman}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
      show_sql: true
  zipkin:
    base-url: http://${ZIPKIN_IP:zipkin}:9411/

server:
  port: 8086

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_SERVER_IP:eureka-server}:8761/eureka-server

rabbitmq:
  topic-exchanges:
      name: internal.exchange
  queues:
    name:
      notification: notification.queue
  routing-keys:
    name:
      notification: notification.routing.key





